apiVersion: v1
kind: Secret
metadata:
    name: user-secret
    namespace: app
data:
    url: jdbc:postgresql://postgresql-service:5432/dashboard_app
    username: dXNlcl9zZXJ2aWNl  # base64 encoded 'user_service'
    password: Z3JnanVISOE5  # base64 encoded 'grgjUHI9'
    email: kritsami181@gmail.com
    password: saminahawand
type: Opaque