apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: user-dashboard
  name: user-dashboard
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-dashboard
    spec:
      containers:
      - image: docker.io/4arctic1/user-dashboard
        imagePullPolicy: Always
        name: user-dashboard
        ports:
        - containerPort: 5000  # Port exposed by the Flask app
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      securityContext: 
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      serviceAccount: default
      nodeName: minikube
      priority: 0
      enableServiceLinks: true
      preemptionPolicy: PreemptLowerPriority
      topologySpreadConstraints: []
      tolerations: []
      hostAliases: []
      - ip: " 
        hostnames:
        - "minikube"
      - ip: "
        hostnames:
        - "docker-desktop"