apiVersion: v1
kind: Secret
metadata:
  name: timesheet-secret
  namespace: app
data:
  url: jdbc:postgresql://postgresql-service:5432/dashboard_app
  username: dGltZXNoZWV0X3VzZXI=  # base64 encoded 'timesheet_user'
  password: cm9vdHB3ZA==  # base64 encoded 'rootpwd'
type: Opaque
