apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd
        image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/<ecr repo>:<tag>
        ports:
        - containerPort: 5000