version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: timesheet_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard_app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dashboard_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: grgjUHI9
      SERVER_PORT: 7070

  timesheet-service:
    build: ./timesheet-service
    container_name: timesheet-service
    restart: always
    ports:
      - "7071:7071"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dashboard_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: grgjUHI9
      SERVER_PORT: 7071

  leave-service:
    build: ./leave-service
    container_name: leave-service
    restart: always
    ports:
      - "7072:7072"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dashboard_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: grgjUHI9
      SERVER_PORT: 7072

  frontend:
    build: ./timesheet-frontend
    container_name: dashboard-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - timesheet-service
      - leave-service

volumes:
  postgres-data:
