server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:7070
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: timesheet-service
          uri: http://localhost:7071
          predicates:
            - Path=/api/timesheets/**
          filters:
            - RewritePath=/api/timesheets/(?<segment>.*), /${segment}

        - id: leave-service
          uri: http://localhost:7072
          predicates:
            - Path=/api/leave/**
          filters:
            - RewritePath=/api/leave/(?<segment>.*), /${segment}

        - id: sickness-service
          uri: http://localhost:7073
          predicates:
            - Path=/api/sickness/**
          filters:
            - RewritePath=/api/sickness/(?<segment>.*), /${segment}